// Data-layer switch: the server API is the default; set VITE_MOCK=1 to run
// the UI standalone on the in-browser mock (no server needed).

import * as mock from './mockApi'
import * as server from './serverApi'

const impl = import.meta.env.VITE_MOCK === '1' ? mock : server

export const {
  subscribe,
  getItems,
  getSync,
  getCurrentUser,
  login,
  logout,
  googleLoginUrl,
  regenerateGatePin,
  listApiTokens,
  createApiToken,
  revokeApiToken,
  getProjects,
  getActiveProjectId,
  getFarm,
  getDurationEstimates,
  setProjectEnabled,
  setProjectAutopilot,
  saveToken,
  createProject,
  addRepoToProject,
  disconnectRepo,
  saveRepoChecks,
  getRepoCheckDefaults,
  getRepoWebhooks,
  fixRepoWebhook,
  createItem,
  artifactUrl,
  outputUrl,
  runLogViewUrl,
  issueUrl,
  issueLabel,
  approveGate,
  requestChanges,
  resolveConflicts,
  forwardToAccept,
  togglePause,
  restartPhase,
  setPersona,
  abandonItem,
  listDefinitions,
  getDefinition,
  saveDefinition,
  effectivePrompt,
  listRuleTargets,
  listRuleVersions,
  saveRule,
  restoreRule,
  getDeployTargets,
  dryRunDeployTarget,
  getDeployTargetConfig,
  createDeployTarget,
  updateDeployTarget,
  deleteDeployTarget,
} = impl
