// GENERATED by domain/generate.mjs — do not edit.
// Source: domain/steps.json + domain/templates/. Regenerate: npm run gen:domain
// The one JS view of "what is a lifecycle step" — imported by relative path
// from server/src, ui/src and e2e/. Before HZ-128 this logic existed twice:
// server/src/lifecycle.js and ui/src/domain/lifecycle.js, with isClosed and
// curStep byte-identical and the index lookup differing only in name and
// argument order (requiredStepIndex(label, steps) vs requiredIndex(steps,
// label)). One copy now, one name, one argument order.
//
// The step DATA below is inlined as a literal on purpose: the UI must work
// with no server and no runtime fetch (see ui/src/api/mockApi.js), and Vite's
// production build must not have to resolve a JSON import from outside its
// root. Nothing presentational lives here — AGENTS colours, PHASE_ACCENT*
// and PRIORITY_COLORS stay hand-owned in the UI (ui/src/domain/lifecycle.js,
// ui/src/domain/agentTokens.js).

export const PHASES = [
  "Plan",
  "Technical Plan",
  "Execute",
  "Deploy",
  "Review"
]

// runsIn: which long-running process executes the step — 'pm' (the project's
// persistent PM session) or 'farm' (an ephemeral agent dispatched by farmd's
// queue). Only meaningful for kind: 'agent' entries.
// workspaceMutating/providerOverrideEligible/providerLocked/maxTurns/timeoutS
// are farm-only fields, declared only on runsIn: 'farm' entries — the PM
// agent uses its own budget mechanism (farm/pm_agent.py), out of scope here.
// requires (HZ-105): labels of prior steps whose artifact this step cannot
// review without in full. Checked by orchestrator.js's dispatchToFarm gate
// (missingRequiredInputs) before a farm dispatch — if the artifact budget had
// to truncate a required artifact, the step never runs. Omit for steps that
// tolerate a truncated/absent prior artifact.
export const STEPS = [
  {
    "phase": 0,
    "kind": "agent",
    "agent": "PM",
    "label": "Define the outcome",
    "runsIn": "pm"
  },
  {
    "phase": 0,
    "kind": "agent",
    "agent": "PM",
    "label": "Define how we measure success",
    "runsIn": "pm"
  },
  {
    "phase": 0,
    "kind": "agent",
    "agent": "Architect",
    "label": "Set guardrails",
    "runsIn": "pm"
  },
  {
    "phase": 0,
    "kind": "gate",
    "gate": "required",
    "label": "Approve & prioritize this work"
  },
  {
    "phase": 1,
    "kind": "agent",
    "agent": "Ensemble",
    "label": "Plan options & trade-offs (pros / cons)",
    "runsIn": "farm",
    "workspaceMutating": false,
    "providerOverrideEligible": true,
    "providerLocked": false,
    "maxTurns": 40,
    "timeoutS": 1140
  },
  {
    "phase": 1,
    "kind": "gate",
    "gate": "required",
    "label": "Approve the high-level design"
  },
  {
    "phase": 1,
    "kind": "agent",
    "agent": "Eng",
    "label": "Draft implementation plan",
    "runsIn": "farm",
    "workspaceMutating": false,
    "providerOverrideEligible": true,
    "providerLocked": false,
    "maxTurns": 40,
    "timeoutS": 1140
  },
  {
    "phase": 1,
    "kind": "agent",
    "agent": "Architect",
    "label": "Architecture review",
    "runsIn": "farm",
    "workspaceMutating": false,
    "providerOverrideEligible": true,
    "providerLocked": false,
    "maxTurns": 40,
    "timeoutS": 1140,
    "requires": [
      "Draft implementation plan"
    ]
  },
  {
    "phase": 1,
    "kind": "agent",
    "agent": "QA",
    "label": "QA reviews the test plan",
    "runsIn": "farm",
    "workspaceMutating": false,
    "providerOverrideEligible": false,
    "providerLocked": false,
    "maxTurns": 40,
    "timeoutS": 1140,
    "requires": [
      "Draft implementation plan"
    ]
  },
  {
    "phase": 1,
    "kind": "agent",
    "agent": "PM",
    "label": "Summarize reviews & recommend",
    "runsIn": "pm"
  },
  {
    "phase": 1,
    "kind": "gate",
    "gate": "required",
    "label": "Review before execution"
  },
  {
    "phase": 2,
    "kind": "agent",
    "agent": "Eng",
    "label": "Specialist agent implements",
    "runsIn": "farm",
    "workspaceMutating": true,
    "providerOverrideEligible": false,
    "providerLocked": true,
    "maxTurns": 160,
    "timeoutS": 2700
  },
  {
    "phase": 2,
    "kind": "agent",
    "agent": "Review",
    "label": "Automated review (code + QA)",
    "runsIn": "farm",
    "workspaceMutating": true,
    "providerOverrideEligible": false,
    "providerLocked": false,
    "maxTurns": 60,
    "timeoutS": 1800
  },
  {
    "phase": 2,
    "kind": "gate",
    "gate": "required",
    "label": "Accept the code"
  },
  {
    "phase": 3,
    "kind": "agent",
    "agent": "DevOps",
    "label": "Deploy the changes",
    "runsIn": "farm",
    "workspaceMutating": false,
    "providerOverrideEligible": false,
    "providerLocked": true,
    "maxTurns": 40,
    "timeoutS": 900
  },
  {
    "phase": 4,
    "kind": "gate",
    "gate": "required",
    "label": "Review the work & close"
  }
]

// Derived, never hardcoded elsewhere — a future step insertion only has to
// change domain/steps.json; every index-dependent call site re-resolves
// itself. Throws rather than yielding -1 (silently pointing at the wrong
// step) if a label is renamed without updating its call site.
export function requiredStepIndex(label, steps = STEPS) {
  const index = steps.findIndex((s) => s.label === label)
  if (index === -1) throw new Error(`lifecycle: no step labeled "${label}" — was it renamed?`)
  return index
}

export const IMPLEMENT_STEP_INDEX = requiredStepIndex('Specialist agent implements')
export const REVIEW_STEP_INDEX = requiredStepIndex('Automated review (code + QA)')
export const ACCEPT_GATE_INDEX = requiredStepIndex('Accept the code')
export const DEPLOY_STEP_INDEX = requiredStepIndex('Deploy the changes')

// Every agent-kind step index, in order — the derived default for
// FARM_STEP_INDEXES (server/src/config.js retains the env override on top).
export function agentStepIndexes(steps = STEPS) {
  return steps.map((s, i) => (s.kind === 'agent' ? i : -1)).filter((i) => i >= 0)
}

// ---- derived state ----

export function isClosed(item) {
  return item.cursor >= STEPS.length
}

// A human-initiated soft delete (HZ-59) — deliberately independent of cursor
// so an abandoned item is never mistaken for one that reached the final gate.
export function isAbandoned(item) {
  return !!item.abandoned_at
}

export function curStep(item) {
  return isClosed(item) ? null : STEPS[item.cursor]
}

export function phaseIdx(item) {
  return isClosed(item) ? 4 : STEPS[item.cursor].phase
}

export function awaitingGate(item) {
  if (isAbandoned(item)) return false
  const c = curStep(item)
  return !!c && c.kind === 'gate' && !item.rejected
}

export function stepStatus(item, i) {
  if (isClosed(item)) return 'done'
  if (item.rejected && i === item.cursor) return 'blocked'
  if (i < item.cursor) return 'done'
  if (i === item.cursor) return STEPS[i].kind === 'gate' ? 'awaiting' : 'active'
  return 'pending'
}

export function phaseStepIndexes(phase) {
  return STEPS.map((s, i) => (s.phase === phase ? i : -1)).filter((i) => i >= 0)
}

// Dependencies (HZ-78). `blockers` is the array of work_item rows this item
// depends on (already fetched by the caller — this stays a pure function over
// rows, same as isClosed/isAbandoned above). A dependency is satisfied only by
// the blocker CLOSING — paused, mid-flight, rejected, or abandoned all still
// count as blocking. Abandoned blockers do not unblock silently:
// isBlockedByAbandoned lets the caller surface that case distinctly instead of
// letting it read as an ordinary in-progress blocker.
export function isBlocked(blockers) {
  return blockers.some((b) => !isClosed(b))
}

export function isBlockedByAbandoned(blockers) {
  return blockers.some((b) => isAbandoned(b))
}

// ---- send-back-to-a-chosen-step (HZ-51) ----
// Eligible destinations for a send-back from the gate at gateIndex: every
// agent step strictly earlier than it, derived from STEPS so a pipeline change
// (insertion/reorder) never needs a hardcoded index here. The server
// re-derives and enforces the same rule independently — this is for populating
// the picker, not the source of truth.
export function reworkTargets(gateIndex) {
  return STEPS.map((s, i) => ({ index: i, label: s.label })).filter(
    ({ index }) => index < gateIndex && STEPS[index].kind === 'agent',
  )
}

// Mirrors the server's default (no-target) destination, purely so the picker
// can show what "default" means — the actual default routing happens
// server-side when no target is sent.
export function defaultReworkTarget(gateIndex) {
  if (gateIndex === ACCEPT_GATE_INDEX) return IMPLEMENT_STEP_INDEX
  let idx = gateIndex
  while (idx > 0 && STEPS[idx].kind !== 'agent') idx--
  return idx
}
