# GENERATED by domain/generate.mjs — do not edit.
# Source: domain/steps.json + domain/templates/. Regenerate: npm run gen:domain
"""The farm's one view of "what is a lifecycle step" (HZ-117, relocated by
HZ-128).

The table below is generated from domain/steps.json — the only place a step is
declared — so this module never hand-duplicates a second table. Every farm
module that used to hardcode a step index -> (budget | provider rule | lane |
workspace-mutating) mapping (farm/step_agent.py's
STEP_CONFIG/PROVIDER_OVERRIDE_ELIGIBLE_STEPS, farm/farmd.py's
WORKSPACE_MUTATING_STEPS and lane routing) reads it from here.

This is the farm-shaped projection: agent-kind entries ONLY (both the PM lane
and the farm lane — farmd's /steps/run needs runsIn for both to route
correctly), each carrying its own `index` into the full table. The farm-only
fields are None on runsIn 'pm' entries, which never reach step_agent.py's
budget/provider lookups. Gates are absent entirely: the farm never dispatches
one.

The derivation functions (budget_for_label, provider_override_eligible,
provider_locked_for) take `steps` as their first argument rather than reading
the module-level STEPS global internally — that's what lets a test fabricate a
step table (e.g. with an inserted step) and assert the derivation follows it,
with zero literal indices in the test itself.
"""

import json
from pathlib import Path

PHASES: list[str] = [
    "Plan",
    "Technical Plan",
    "Execute",
    "Deploy",
    "Review",
]


def _validate_steps(data: list, source: str) -> list[dict]:
    """Shape + duplicate-label enforcement, applied to the embedded table at
    import time AND to anything _load_steps reads off disk. Raises rather than
    returning a partly-usable table: a duplicate label would make
    _find_by_label silently resolve to whichever entry came first."""
    if not isinstance(data, list) or not all(isinstance(entry, dict) for entry in data):
        raise RuntimeError(f"domain/py/steps.py: {source} must be a JSON array of step objects")
    labels = [entry.get("label") for entry in data]
    dupes = {label for label in labels if labels.count(label) > 1}
    if dupes:
        raise RuntimeError(f"domain/py/steps.py: {source} has duplicate step label(s): {sorted(dupes)}")
    return data


def _load_steps(path: Path) -> list[dict]:
    """Reads a farm-shaped step table off disk and validates it.

    Kept deliberately even though the production table below is embedded, not
    loaded: farm/tests/test_steps.py exercises all four failure modes
    (unreadable, malformed, non-array, duplicate labels) through this
    function. Recorded as an accepted wart in domain/README.md."""
    try:
        raw = path.read_text()
    except OSError as exc:
        raise RuntimeError(
            f"domain/py/steps.py: could not read {path} — run `npm run gen:domain` ({exc})"
        ) from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"domain/py/steps.py: {path} is not valid JSON — regenerate it ({exc})") from exc
    return _validate_steps(data, str(path))


STEPS: list[dict] = _validate_steps([
    {
        "index": 0,
        "label": "Define the outcome",
        "agent": "PM",
        "runsIn": "pm",
        "workspaceMutating": None,
        "providerOverrideEligible": None,
        "providerLocked": None,
        "maxTurns": None,
        "timeoutS": None,
    },
    {
        "index": 1,
        "label": "Define how we measure success",
        "agent": "PM",
        "runsIn": "pm",
        "workspaceMutating": None,
        "providerOverrideEligible": None,
        "providerLocked": None,
        "maxTurns": None,
        "timeoutS": None,
    },
    {
        "index": 2,
        "label": "Set guardrails",
        "agent": "Architect",
        "runsIn": "pm",
        "workspaceMutating": None,
        "providerOverrideEligible": None,
        "providerLocked": None,
        "maxTurns": None,
        "timeoutS": None,
    },
    {
        "index": 4,
        "label": "Plan options & trade-offs (pros / cons)",
        "agent": "Ensemble",
        "runsIn": "farm",
        "workspaceMutating": False,
        "providerOverrideEligible": True,
        "providerLocked": False,
        "maxTurns": 40,
        "timeoutS": 1140,
    },
    {
        "index": 6,
        "label": "Draft implementation plan",
        "agent": "Eng",
        "runsIn": "farm",
        "workspaceMutating": False,
        "providerOverrideEligible": True,
        "providerLocked": False,
        "maxTurns": 40,
        "timeoutS": 1140,
    },
    {
        "index": 7,
        "label": "Architecture review",
        "agent": "Architect",
        "runsIn": "farm",
        "workspaceMutating": False,
        "providerOverrideEligible": True,
        "providerLocked": False,
        "maxTurns": 40,
        "timeoutS": 1140,
    },
    {
        "index": 8,
        "label": "QA reviews the test plan",
        "agent": "QA",
        "runsIn": "farm",
        "workspaceMutating": False,
        "providerOverrideEligible": False,
        "providerLocked": False,
        "maxTurns": 40,
        "timeoutS": 1140,
    },
    {
        "index": 9,
        "label": "Summarize reviews & recommend",
        "agent": "PM",
        "runsIn": "pm",
        "workspaceMutating": None,
        "providerOverrideEligible": None,
        "providerLocked": None,
        "maxTurns": None,
        "timeoutS": None,
    },
    {
        "index": 11,
        "label": "Specialist agent implements",
        "agent": "Eng",
        "runsIn": "farm",
        "workspaceMutating": True,
        "providerOverrideEligible": False,
        "providerLocked": True,
        "maxTurns": 160,
        "timeoutS": 2700,
    },
    {
        "index": 12,
        "label": "Automated review (code + QA)",
        "agent": "Review",
        "runsIn": "farm",
        "workspaceMutating": True,
        "providerOverrideEligible": False,
        "providerLocked": False,
        "maxTurns": 60,
        "timeoutS": 1800,
    },
    {
        "index": 14,
        "label": "Deploy the changes",
        "agent": "DevOps",
        "runsIn": "farm",
        "workspaceMutating": False,
        "providerOverrideEligible": False,
        "providerLocked": True,
        "maxTurns": 40,
        "timeoutS": 900,
    },
], "domain/steps.json")

# Safe .get()-only lookup — farmd's dispatch loop reads task payloads off the
# network and must never raise on an unknown/stale index.
STEP_BY_INDEX: dict[int, dict] = {entry["index"]: entry for entry in STEPS}


def _find_by_label(steps: list[dict], label: str) -> dict:
    """The one step entry with this label. Raises KeyError naming the label
    (never returns a wrong/blank result) if it isn't in the table — e.g. the
    label was renamed on one side of the JS/Python boundary but not the
    other."""
    for entry in steps:
        if entry["label"] == label:
            return entry
    raise KeyError(f"no step labeled {label!r} in the generated step table — run `npm run gen:domain`")


def by_label(label: str) -> dict:
    """Convenience wrapper over the module's own STEPS — real call sites use
    this; tests that need a fabricated table call the pure functions below
    directly with their own `steps` list instead."""
    return _find_by_label(STEPS, label)


def budget_for_label(steps: list[dict], label: str) -> tuple[int, int]:
    """(max_turns, timeout_s) for a farm-run step."""
    entry = _find_by_label(steps, label)
    return entry["maxTurns"], entry["timeoutS"]


def provider_override_eligible(steps: list[dict], label: str) -> bool:
    """Whether a persona-forced provider override (farm/personas.py's
    provider_for()) is honored for this step. HZ-102 guardrail: this must be
    False for implement/deploy no matter what a persona maps to — enforced
    here by construction (their table entries carry providerOverrideEligible:
    false), not by a separate allowlist that could drift from STEPS."""
    return bool(_find_by_label(steps, label)["providerOverrideEligible"])


def provider_locked_for(steps: list[dict], label: str) -> bool:
    """Whether this step must refuse ANY non-default provider, including a
    bare FARM_PROVIDER env override — closes the hole a persona-only check
    would miss. Passed into every run_agent() call the step makes."""
    return bool(_find_by_label(steps, label)["providerLocked"])
