// HZ-128: renders every language binding from domain/steps.json — the one
// place a lifecycle step is declared.
//
//   npm run gen:domain            (== node domain/generate.mjs --write)
//   node domain/generate.mjs --check
//
// --write regenerates domain/js/lifecycle.js and domain/py/steps.py from
// domain/templates/. --check re-renders in memory and exits non-zero if a
// committed binding differs, naming the file: that is what makes "bindings are
// generated, never hand-edited" enforceable rather than aspirational. Both the
// zero-diff check and the schema's negative cases are asserted in
// server/test/domain-bindings-zero-diff.test.mjs and
// server/test/domain-schema.test.mjs, so `npm test` catches a stale binding
// without anyone remembering to run this by hand.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'

import { validate } from './validate.mjs'

export const DOMAIN_DIR = import.meta.dirname
export const REPO_ROOT = path.resolve(DOMAIN_DIR, '..')

const BANNER_TEXT = [
  'GENERATED by domain/generate.mjs — do not edit.',
  'Source: domain/steps.json + domain/templates/. Regenerate: npm run gen:domain',
]

// Every generated target: which template renders it, and how a comment starts
// in that language (the banner is the only language-dependent bit).
const TARGETS = [
  { out: 'js/lifecycle.js', template: 'templates/lifecycle.js.tmpl', comment: '//', shape: 'authored' },
  { out: 'py/steps.py', template: 'templates/steps.py.tmpl', comment: '#', shape: 'farm' },
]

function readJson(file) {
  return JSON.parse(readFileSync(file, 'utf8'))
}

// Reads and fully validates the authored source. Throws — never returns a
// partly-valid table — so every caller (the CLI, the parity test, the zero-diff
// test) gets the same guarantee without repeating the checks.
//
// `domainDir` exists so a test can point the REAL function at a tampered copy
// of domain/ in a temp dir, rather than re-implementing these checks in the
// test (which would then be testing a copy of the logic, not the logic).
export function loadSource(domainDir = DOMAIN_DIR) {
  const sourcePath = path.join(domainDir, 'steps.json')
  const named = path.relative(REPO_ROOT, sourcePath) || sourcePath
  const schema = readJson(path.join(domainDir, 'steps.schema.json'))
  const source = readJson(sourcePath)

  const errors = validate(schema, source)
  if (errors.length > 0) {
    throw new Error(`${named} does not satisfy domain/steps.schema.json:\n  - ${errors.join('\n  - ')}`)
  }

  // Cross-field rules a Draft-07 subset cannot express. Both are real hazards,
  // not hypotheticals: a duplicate label makes requiredStepIndex and
  // steps.py's _find_by_label silently resolve to whichever entry came first,
  // and a phase past the end of `phases` renders as `undefined` in the UI's
  // phase header.
  const labels = source.steps.map((s) => s.label)
  const dupes = [...new Set(labels.filter((l, i) => labels.indexOf(l) !== i))].sort()
  if (dupes.length > 0) {
    throw new Error(`${named} has duplicate step label(s): ${JSON.stringify(dupes)}`)
  }
  for (const [i, step] of source.steps.entries()) {
    if (step.phase >= source.phases.length) {
      throw new Error(
        `${named}: steps[${i}] ("${step.label}") declares phase ${step.phase}, but only ${source.phases.length} phase(s) exist`,
      )
    }
  }

  return source
}

// Farm-shaped view: every agent-kind step (both the PM lane and the farm lane —
// farmd's /steps/run needs runsIn for BOTH to route correctly), with every
// field domain/py/steps.py needs to derive lane routing, budgets and provider
// rules. The farm-only fields (workspaceMutating..timeoutS) are null on
// runsIn 'pm' entries, which never reach step_agent.py's budget/provider
// lookups. `requires` is deliberately dropped: it gates a server-side dispatch
// decision, never a farm one.
export function toGeneratedSteps(steps) {
  return steps
    .map((s, index) => ({ ...s, index }))
    .filter((s) => s.kind === 'agent')
    .map((s) => ({
      index: s.index,
      label: s.label,
      agent: s.agent,
      runsIn: s.runsIn,
      workspaceMutating: s.workspaceMutating ?? null,
      providerOverrideEligible: s.providerOverrideEligible ?? null,
      providerLocked: s.providerLocked ?? null,
      maxTurns: s.maxTurns ?? null,
      timeoutS: s.timeoutS ?? null,
    }))
}

// ---- rendering ----

function banner(comment) {
  return BANNER_TEXT.map((line) => `${comment} ${line}`).join('\n')
}

function jsLiteral(value) {
  return JSON.stringify(value, null, 2)
}

// JSON is not quite Python: true/false/null differ. Emitted with a stable
// 4-space step so --check stays byte-exact across runs.
function pyLiteral(value, indent = 0) {
  const pad = ' '.repeat(indent)
  const inner = ' '.repeat(indent + 4)
  if (value === null) return 'None'
  if (value === true) return 'True'
  if (value === false) return 'False'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'string') return JSON.stringify(value)
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const items = value.map((v) => `${inner}${pyLiteral(v, indent + 4)}`)
    return `[\n${items.join(',\n')},\n${pad}]`
  }
  const entries = Object.entries(value)
  if (entries.length === 0) return '{}'
  const items = entries.map(([k, v]) => `${inner}${JSON.stringify(k)}: ${pyLiteral(v, indent + 4)}`)
  return `{\n${items.join(',\n')},\n${pad}}`
}

// relPath (from the repo root) -> exact file contents. Returning a map rather
// than writing is what lets the zero-diff test compare in-process, with the
// subprocess `--check` covered separately.
export function renderAll(domainDir = DOMAIN_DIR) {
  const source = loadSource(domainDir)
  const farmSteps = toGeneratedSteps(source.steps)
  const rendered = new Map()

  for (const target of TARGETS) {
    const template = readFileSync(path.join(domainDir, target.template), 'utf8')
    const steps = target.shape === 'farm' ? farmSteps : source.steps
    const stepsLiteral = target.comment === '#' ? pyLiteral(steps) : jsLiteral(steps)
    const phasesLiteral =
      target.comment === '#' ? pyLiteral(source.phases) : jsLiteral(source.phases)

    const body = template
      .replace('@@HEADER@@', banner(target.comment))
      .replace('@@PHASES@@', phasesLiteral)
      .replace('@@STEPS@@', stepsLiteral)

    if (body.includes('@@')) {
      throw new Error(`domain/generate.mjs: unreplaced @@TOKEN@@ left in ${target.out}`)
    }
    // LF only, exactly one trailing newline — byte stability is what makes
    // --check a real guarantee instead of a whitespace lottery.
    rendered.set(`domain/${target.out}`, `${body.replace(/\r\n/g, '\n').replace(/\n+$/, '')}\n`)
  }

  return rendered
}

// ---- CLI ----

function main(argv) {
  const mode = argv[0]
  if (mode !== '--write' && mode !== '--check') {
    console.error('usage: node domain/generate.mjs --write | --check')
    return 1
  }

  const rendered = renderAll()

  if (mode === '--write') {
    for (const [relPath, contents] of rendered) {
      const full = path.join(REPO_ROOT, relPath)
      mkdirSync(path.dirname(full), { recursive: true })
      writeFileSync(full, contents)
      console.log(`wrote ${relPath}`)
    }
    return 0
  }

  const stale = []
  for (const [relPath, contents] of rendered) {
    let onDisk = null
    try {
      onDisk = readFileSync(path.join(REPO_ROOT, relPath), 'utf8')
    } catch {
      stale.push(`${relPath} is missing`)
      continue
    }
    if (onDisk !== contents) stale.push(`${relPath} differs from a fresh render`)
  }

  if (stale.length > 0) {
    console.error('domain bindings are stale or hand-edited:')
    for (const line of stale) console.error(`  - ${line}`)
    console.error('run `npm run gen:domain` (and edit domain/steps.json or domain/templates/, never the output)')
    return 1
  }
  console.log(`domain bindings are up to date (${rendered.size} file(s) checked)`)
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  process.exit(main(process.argv.slice(2)))
}
