// HZ-128 success criterion 4 and guardrail 6: "bindings are generated, never
// hand-edited. Re-running the generator produces a zero-length diff, asserted
// in CI."
//
// This runs inside `npm test`, which farm/checks.py detects at the repo root —
// so a hand-edited or stale binding fails the guardrail gate without anyone
// having to remember `node domain/generate.mjs --check`.
//
// The NEGATIVE CONTROL at the bottom is the part that makes this a real
// assertion: a --check that always exited 0 would pass every case above. It
// copies domain/ to a temp dir, hand-edits a binding there, and asserts --check
// exits 1 naming the file it touched. The real domain/ is never written to.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, writeFileSync, appendFileSync, mkdtempSync, cpSync, rmSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { renderAll, REPO_ROOT } from '../../domain/generate.mjs'

const GENERATOR = path.join(REPO_ROOT, 'domain/generate.mjs')

function tempDomain() {
  const dir = path.join(mkdtempSync(path.join(tmpdir(), 'horizon-zerodiff-')), 'domain')
  cpSync(path.join(REPO_ROOT, 'domain'), dir, { recursive: true })
  return dir
}

function runGenerator(generatorPath, flag) {
  return spawnSync(process.execPath, [generatorPath, flag], { encoding: 'utf8' })
}

const rendered = renderAll()

test('the generator renders exactly the two committed bindings, and nothing else', () => {
  assert.deepEqual([...rendered.keys()].sort(), ['domain/js/lifecycle.js', 'domain/py/steps.py'])
})

test('every committed binding is byte-identical to a fresh render', () => {
  for (const [relPath, expected] of rendered) {
    const onDisk = readFileSync(path.join(REPO_ROOT, relPath), 'utf8')
    assert.equal(
      onDisk,
      expected,
      `${relPath} differs from a fresh render — it was hand-edited, or domain/steps.json changed without \`npm run gen:domain\``,
    )
  }
})

test('every generated file is LF-only and ends in exactly one newline', () => {
  for (const [relPath, contents] of rendered) {
    assert.ok(!contents.includes('\r'), `${relPath} contains a CR`)
    assert.ok(contents.endsWith('\n'), `${relPath} has no trailing newline`)
    assert.ok(!contents.endsWith('\n\n'), `${relPath} ends in more than one newline`)
  }
})

test('every generated file opens with the do-not-edit banner naming the source and the regen command', () => {
  for (const [relPath, contents] of rendered) {
    const head = contents.split('\n').slice(0, 2).join('\n')
    assert.match(head, /GENERATED by domain\/generate\.mjs — do not edit\./, `${relPath} has no banner`)
    assert.match(head, /domain\/steps\.json/, `${relPath}'s banner does not name the source`)
    assert.match(head, /npm run gen:domain/, `${relPath}'s banner does not name the regen command`)
  }
})

test('node domain/generate.mjs --check exits 0 against the committed tree', () => {
  const result = runGenerator(GENERATOR, '--check')
  assert.equal(result.status, 0, `--check failed:\n${result.stdout}${result.stderr}`)
})

test('the generator is idempotent: a second --write changes no bytes', () => {
  const dir = tempDomain()
  const generator = path.join(dir, 'generate.mjs')
  const target = path.join(dir, 'js/lifecycle.js')

  assert.equal(runGenerator(generator, '--write').status, 0)
  const first = readFileSync(target, 'utf8')
  assert.equal(runGenerator(generator, '--write').status, 0)
  assert.equal(readFileSync(target, 'utf8'), first, 'a second --write produced different bytes')
  assert.equal(runGenerator(generator, '--check').status, 0)
})

test('NEGATIVE CONTROL: --check exits non-zero and names the file when a binding is hand-edited', () => {
  const dir = tempDomain()
  appendFileSync(path.join(dir, 'js/lifecycle.js'), '\n// hand-edited\n')

  const result = runGenerator(path.join(dir, 'generate.mjs'), '--check')
  assert.equal(result.status, 1, '--check accepted a hand-edited binding')
  assert.match(result.stderr, /domain\/js\/lifecycle\.js/)
  assert.match(result.stderr, /npm run gen:domain/)
})

test('NEGATIVE CONTROL: --check exits non-zero when a binding is missing entirely', () => {
  const dir = tempDomain()
  rmSync(path.join(dir, 'py/steps.py'))

  const result = runGenerator(path.join(dir, 'generate.mjs'), '--check')
  assert.equal(result.status, 1)
  assert.match(result.stderr, /domain\/py\/steps\.py is missing/)
})

test('NEGATIVE CONTROL: --check exits non-zero when the SOURCE changed but the bindings were not regenerated', () => {
  const dir = tempDomain()
  const source = JSON.parse(readFileSync(path.join(dir, 'steps.json'), 'utf8'))
  // An AGENT step, so both bindings go stale — a gate would only change the JS
  // one, since gates never reach the farm view.
  source.steps.push({
    phase: 4,
    kind: 'agent',
    agent: 'Eng',
    label: 'A Step Nobody Regenerated',
    runsIn: 'farm',
    workspaceMutating: false,
    providerOverrideEligible: false,
    providerLocked: false,
    maxTurns: 1,
    timeoutS: 1,
  })
  writeFileSync(path.join(dir, 'steps.json'), `${JSON.stringify(source, null, 2)}\n`)

  const result = runGenerator(path.join(dir, 'generate.mjs'), '--check')
  assert.equal(result.status, 1, 'a stale binding passed --check')
  assert.match(result.stderr, /domain\/js\/lifecycle\.js/)
  assert.match(result.stderr, /domain\/py\/steps\.py/)
})

test('the generator refuses an unknown flag rather than doing something surprising', () => {
  const result = runGenerator(GENERATOR, '--wipe')
  assert.equal(result.status, 1)
  assert.match(result.stderr, /usage: node domain\/generate\.mjs --write \| --check/)
})
